settings:
  bot_name: chat
  command_name: gpt
  api_key: SECRET
  endpoint: https://openrouter.ai/api/v1/chat/completions
  system_prompt: You are a helpful assistant.
  model: deepseek-chat
  max_tokens: 500
  temperature: 1
  reply: False
  enable_global_rate_limit: True
  global_rate_limit: 100
  enable_user_rate_limit: True
  user_rate_limit: 100
  enable_input_character_limit: True
  input_character_limit: 250

  # rate limit is rolling, rate instances last 24hrs.
